name: glide_file_demo
description: Demo frontend de la app Glide-File
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0-54.0.dev <4.0.0'

dependencies:
  get:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_beacon: ^0.5.1
  permission_handler: ^10.2.0
  flutter_bluetooth_serial: ^0.4.0
  device_info_plus: ^9.1.1
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Mukta
      fonts:
        - asset: resources/assets/fonts/Mukta-Bold.ttf
        - asset: resources/assets/fonts/Mukta-ExtraBold.ttf
        - asset: resources/assets/fonts/Mukta-Light.ttf
        - asset: resources/assets/fonts/Mukta-Medium.ttf
        - asset: resources/assets/fonts/Mukta-Regular.ttf
    - family: LobsterTwo
      fonts:
        - asset: resources/assets/fonts/LobsterTwo-Bold.ttf
        - asset: resources/assets/fonts/LobsterTwo-BoldItalic.ttf
        - asset: resources/assets/fonts/LobsterTwo-Italic.ttf
        - asset: resources/assets/fonts/LobsterTwo-Regular.ttf

  assets:
    - resources/icons/
    - resources/assets/splash.riv